### ISSUE TITLE
Pretested Commits sollen mit einer neueren SonarQube Version funktionieren

### ISSUE THREAD

**Issue by mibeumer** [mirkosertic/mavensonarsputnik#10]
Es wäre schön wenn die Pretested Commits auch mit einer neueren SonarQube Version (5.6 LTS) funktionieren würden.

Insbesondere dieses Maven Sonar Sputnik Plugin muss dafür angepasst werden.

Nach dem Upgrade von Sonar 4.5.6 auf 4.5.7 führt das Ausführen des API-Manager Applikation Pretested Commit Jenkins Job zu folgender Fehlermeldung:
`
[INFO] Finished at: 2017-02-21T15:43:35+01:00
[INFO] Final Memory: 75M/430M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal de.mirkosertic.mavensonarsputnik:sputnik:1.6:sputnik (default-cli) on project parent: Execution default-cli of goal de.mirkosertic.mavensonarsputnik:sputnik:1.6:sputnik failed: An API incompatibility was encountered while executing de.mirkosertic.mavensonarsputnik:sputnik:1.6:sputnik: java.lang.NoSuchMethodError: com.puppycrawl.tools.checkstyle.Checker.setClassLoader(Ljava/lang/ClassLoader;)V
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>de.mirkosertic.mavensonarsputnik:sputnik:1.6
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/de/mirkosertic/mavensonarsputnik/sputnik/1.6/sputnik-1.6.jar
[ERROR] urls[1] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/org/codehaus/plexus/plexus-utils/3.0.8/plexus-utils-3.0.8.jar
[ERROR] urls[2] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/org/eclipse/aether/aether-util/0.9.0.M2/aether-util-0.9.0.M2.jar
[ERROR] urls[3] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
[ERROR] urls[4] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar
[ERROR] urls[5] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/javax/inject/javax.inject/1/javax.inject-1.jar
[ERROR] urls[6] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/org/sonatype/sisu/sisu-guice/3.1.0/sisu-guice-3.1.0-no_aop.jar
[ERROR] urls[7] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
[ERROR] urls[8] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.0.0.M5/org.eclipse.sisu.inject-0.0.0.M5.jar
[ERROR] urls[9] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/org/codehaus/plexus/plexus-interpolation/1.19/plexus-interpolation-1.19.jar
[ERROR] urls[10] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[11] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[12] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[13] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/pl/touk/sputnik/1.5.1/sputnik-1.5.1.jar
[ERROR] urls[14] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/org/apache/httpcomponents/httpclient/4.3.1/httpclient-4.3.1.jar
[ERROR] urls[15] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/org/apache/httpcomponents/httpcore/4.3/httpcore-4.3.jar
[ERROR] urls[16] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
[ERROR] urls[17] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/pl/gildur/jshint4j/1.0.1/jshint4j-1.0.1.jar
[ERROR] urls[18] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/org/mozilla/rhino/1.7R4/rhino-1.7R4.jar
[ERROR] urls[19] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/org/scalastyle/scalastyle_2.10/0.4.0/scalastyle_2.10-0.4.0.jar
[ERROR] urls[20] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/org/scalariform/scalariform_2.10/0.1.4/scalariform_2.10-0.1.4.jar
[ERROR] urls[21] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/org/scala-lang/scala-library/2.10.0/scala-library-2.10.0.jar
[ERROR] urls[22] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/com/github/scopt/scopt_2.10/3.2.0/scopt_2.10-3.2.0.jar
[ERROR] urls[23] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/org/codehaus/groovy/groovy/2.3.4/groovy-2.3.4.jar
[ERROR] urls[24] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/commons-cli/commons-cli/1.2/commons-cli-1.2.jar
[ERROR] urls[25] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/com/puppycrawl/tools/checkstyle/6.6/checkstyle-6.6.jar
[ERROR] urls[26] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/antlr/antlr/2.7.7/antlr-2.7.7.jar
[ERROR] urls[27] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/org/antlr/antlr4-runtime/4.5/antlr4-runtime-4.5.jar
[ERROR] urls[28] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/org/abego/treelayout/org.abego.treelayout.core/1.0.1/org.abego.treelayout.core-1.0.1.jar
[ERROR] urls[29] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/commons-beanutils/commons-beanutils-core/1.8.3/commons-beanutils-core-1.8.3.jar
[ERROR] urls[30] = file:/mnt/data/java/jdk1.8.0_92/jre/../lib/tools.jar
[ERROR] urls[31] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/com/google/code/findbugs/findbugs/3.0.0/findbugs-3.0.0.jar
[ERROR] urls[32] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/com/google/code/findbugs/bcel-findbugs/6.0/bcel-findbugs-6.0.jar
[ERROR] urls[33] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/com/google/code/findbugs/annotations/3.0.0/annotations-3.0.0.jar
[ERROR] urls[34] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/com/google/code/findbugs/jFormatString/3.0.0/jFormatString-3.0.0.jar
[ERROR] urls[35] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/dom4j/dom4j/1.6.1/dom4j-1.6.1.jar
[ERROR] urls[36] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/org/ow2/asm/asm-debug-all/5.0.2/asm-debug-all-5.0.2.jar
[ERROR] urls[37] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/xml-apis/xml-apis/1.0.b2/xml-apis-1.0.b2.jar
[ERROR] urls[38] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/com/jayway/jsonpath/json-path/0.9.1/json-path-0.9.1.jar
[ERROR] urls[39] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/net/minidev/json-smart/1.2/json-smart-1.2.jar
[ERROR] urls[40] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/org/projectlombok/lombok/1.12.6/lombok-1.12.6.jar
[ERROR] urls[41] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.jar
[ERROR] urls[42] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/com/fasterxml/jackson/core/jackson-databind/2.3.0/jackson-databind-2.3.0.jar
[ERROR] urls[43] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/com/fasterxml/jackson/core/jackson-annotations/2.3.0/jackson-annotations-2.3.0.jar
[ERROR] urls[44] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/com/fasterxml/jackson/core/jackson-core/2.3.0/jackson-core-2.3.0.jar
[ERROR] urls[45] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/com/googlecode/jslint4java/jslint4java/2.0.5/jslint4java-2.0.5.jar
[ERROR] urls[46] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/com/beust/jcommander/1.30/jcommander-1.30.jar
[ERROR] urls[47] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/jaxen/jaxen/1.1.6/jaxen-1.1.6.jar
[ERROR] urls[48] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/org/codenarc/CodeNarc/0.24.1/CodeNarc-0.24.1.jar
[ERROR] urls[49] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/junit/junit/4.8.1/junit-4.8.1.jar
[ERROR] urls[50] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/org/codehaus/groovy/groovy-xml/2.1.8/groovy-xml-2.1.8.jar
[ERROR] urls[51] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/org/codehaus/groovy/groovy-ant/2.1.8/groovy-ant-2.1.8.jar
[ERROR] urls[52] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/org/apache/ant/ant-antlr/1.8.4/ant-antlr-1.8.4.jar
[ERROR] urls[53] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/org/codehaus/groovy/groovy-groovydoc/2.1.8/groovy-groovydoc-2.1.8.jar
[ERROR] urls[54] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/org/codehaus/groovy/groovy-templates/2.1.8/groovy-templates-2.1.8.jar
[ERROR] urls[55] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/org/apache/ant/ant/1.8.4/ant-1.8.4.jar
[ERROR] urls[56] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/org/apache/ant/ant-junit/1.8.4/ant-junit-1.8.4.jar
[ERROR] urls[57] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/org/apache/ant/ant-launcher/1.8.4/ant-launcher-1.8.4.jar
[ERROR] urls[58] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/org/gmetrics/GMetrics/0.7/GMetrics-0.7.jar
[ERROR] urls[59] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/log4j/log4j/1.2.14/log4j-1.2.14.jar
[ERROR] urls[60] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/xerces/xercesImpl/2.9.1/xercesImpl-2.9.1.jar
[ERROR] urls[61] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/org/slf4j/log4j-over-slf4j/1.7.7/log4j-over-slf4j-1.7.7.jar
[ERROR] urls[62] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/ch/qos/logback/logback-classic/1.0.13/logback-classic-1.0.13.jar
[ERROR] urls[63] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/ch/qos/logback/logback-core/1.0.13/logback-core-1.0.13.jar
[ERROR] urls[64] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/com/urswolfer/gerrit/client/rest/gerrit-rest-java-client/0.8.5/gerrit-rest-java-client-0.8.5.jar
[ERROR] urls[65] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/com/google/code/gson/gson/2.3.1/gson-2.3.1.jar
[ERROR] urls[66] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar
[ERROR] urls[67] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/com/intellij/annotations/12.0/annotations-12.0.jar
[ERROR] urls[68] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
[ERROR] urls[69] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/commons-io/commons-io/2.4/commons-io-2.4.jar
[ERROR] urls[70] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/org/sonarsource/scanner/maven/sonar-maven-plugin/3.0.1/sonar-maven-plugin-3.0.1.jar
[ERROR] urls[71] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/org/apache/maven/shared/maven-dependency-tree/2.2/maven-dependency-tree-2.2.jar
[ERROR] urls[72] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/org/sonarsource/sonar-runner/sonar-runner-api/2.5.1/sonar-runner-api-2.5.1.jar
[ERROR] urls[73] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar
[ERROR] urls[74] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/com/google/guava/guava/18.0/guava-18.0.jar
[ERROR] urls[75] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/com/google/code/findbugs/jsr305/2.0.3/jsr305-2.0.3.jar
[ERROR] urls[76] = file:/home/jenkins/workspace/ecp_api_manager_pretestedcommit/.repository/org/twdata/maven/mojo-executor/2.2.0/mojo-executor-2.2.0.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
`

Auch das Update des Maven Plugins auf die 1.7 Version löste das Problem nicht und führt zu einer "FileNotFoundException: sonar-project.properties".

**Comment by mirkosertic** [comment]
Cannot reproduce. Plugin Version 1.7 works with Sonarqube 5.6.6 LTS.
